# Generated by Django 4.2.27 on 2025-12-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
