# Generated by Django 4.2.27 on 2025-12-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_order_orderproduct_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
